[build]
target = "aarch64-unknown-linux-gnu"
rustflags = "-C force-frame-pointers=yes"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
runner = "qemu-aarch64 -L /usr/aarch64-linux-gnu"